### ISSUE TITLE
 userName attribute should be case-insensitive, per the RFC

### ISSUE THREAD

**Issue by logston** [15five/scim2-filter-parser#30]
From https://github.com/15five/django-scim2/issues/76

> See https://datatracker.ietf.org/doc/html/rfc7643#section-4.1.1: (userName)
>     This attribute is REQUIRED and is case insensitive.
> Currently this case-insensitive behavior is not implemented and the filter lookups are case-sensitive.

**Comment by logston** [comment]
To tackle this problem, we need if there is a db agnostic means of comparing two strings in a case insensitive way. For example, do all databases support `UPPER` (ie. `UPPER(email) = `UPPER(test@example.com)`)?

**Comment by andersk** [comment]
`UPPER` is part of the SQL standard, and supported by at least [MySQL](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_upper), [PostgreSQL](https://www.postgresql.org/docs/current/functions-string.html#FUNCTIONS-STRING-SQL), and [SQLite](https://www.sqlite.org/lang_corefunc.html#upper).

**Comment by logston** [comment]
Pushed another set of changes.
