### ISSUE TITLE
Boolean equality expression transpiles to an invalid query in Django + PostgreSQL

### ISSUE THREAD

**Issue by JPDSousa** [15five/scim2-filter-parser#49]
**Describe the bug**
Expressions involving an equality operator and a boolean value fail with `No function matches the given name and argument types. You might need to add explicit type casts.`. This seems to be related with the Django transpiler, and a PostgreSQL database.

**To Reproduce**
Here's a test case that reproduces this behavior:
```python
import pytest
from django.contrib.auth.models import User
from scim2_filter_parser.transpilers.django_q_object import get_query


@pytest.mark.django_db
def test_filter_with_bool_fails() -> None:
    user = User(username='dummy_username', is_active=True)
    user.save()
    query = get_query('active eq true', {('active', None, None): 'is_active'})

    assert list(User.objects.filter(query)) == [user]
```

The test fails with: 
```
(stack trace omited)
E           psycopg.errors.UndefinedFunction: function upper(boolean) does not exist
E           LINE 1: ...ser" WHERE UPPER("auth_user"."is_active"::text) = UPPER(true...
E                                                                        ^
E           HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Environment**:
Python version: 3.11.7
Django version: 4.2.12
scim-filter-parser version: 0.5.1

**Additional context**
Looking at the source code, I see that `scim2_filter_parser.transpilers.django_q_object.Transpiler.lookup_op` ([source](https://github.com/15five/scim2-filter-parser/blob/master/src/scim2_filter_parser/transpilers/django_q_object.py#L220)) will always transpile `eq` into `iexact`, which then seems to generate a `UPPER(field::text) = UPPER(value)`.

It looks like the `ILIKE` -> `UPPER` change in Django comes from [this ticket](https://code.djangoproject.com/ticket/3575). One could argue that this is a Django issue, though with Django we can choose to use `field__exact=True` instead of `field__iexact=True`, whereas here we rely on the `Transpiler` to do that for us.

**Comment by logston** [comment]
Good catch! Unfortunately, we have a very low capacity work on this at the moment. I am happy to review PRs if you would like to make this change.

**Comment by JPDSousa** [comment]
> Good catch! Unfortunately, we have a very low capacity work on this at the moment. I am happy to review PRs if you would like to make this change.

There you go: https://github.com/15five/scim2-filter-parser/pull/53
